<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-OU80H79" failures="2" tests="22" name="Test" time="0.222" errors="0" timestamp="27 Jul 2022 01:05:55 GMT">
  <testcase classname="com.app.testng.FailedTestCases2" name="password" time="0.022">
    <skipped/>
  </testcase> <!-- password -->
  <testcase classname="com.app.testng.FailedTestCases2" name="password" time="0.003">
    <skipped/>
  </testcase> <!-- password -->
  <testcase classname="com.app.testng.FailedTestCases2" name="password" time="0.004">
    <skipped/>
  </testcase> <!-- password -->
  <testcase classname="com.app.testng.FailedTestCases2" name="password" time="0.003">
    <skipped/>
  </testcase> <!-- password -->
  <testcase classname="com.app.testng.FailedTestCases2" name="password" time="0.005">
    <skipped/>
  </testcase> <!-- password -->
  <testcase classname="com.app.testng.FailedTestCases2" name="password" time="0.002">
    <skipped/>
  </testcase> <!-- password -->
  <testcase classname="com.app.testng.FailedTestCases2" name="password" time="0.002">
    <skipped/>
  </testcase> <!-- password -->
  <testcase classname="com.app.testng.FailedTestCases2" name="password" time="0.001">
    <skipped/>
  </testcase> <!-- password -->
  <testcase classname="com.app.testng.FailedTestCases2" name="password" time="0.003">
    <skipped/>
  </testcase> <!-- password -->
  <testcase classname="com.app.testng.FailedTestCases2" name="password" time="0.002">
    <skipped/>
  </testcase> <!-- password -->
  <testcase classname="com.app.testng.FailedTestCases2" name="password" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.app.testng.FailedTestCases2.password(FailedTestCases2.java:17)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- password -->
  <testcase classname="com.app.testng.FailedTestCases2" name="username" time="0.01">
    <skipped/>
  </testcase> <!-- username -->
  <testcase classname="com.app.testng.FailedTestCases2" name="username" time="0.0">
    <skipped/>
  </testcase> <!-- username -->
  <testcase classname="com.app.testng.FailedTestCases2" name="username" time="0.004">
    <skipped/>
  </testcase> <!-- username -->
  <testcase classname="com.app.testng.FailedTestCases2" name="username" time="0.002">
    <skipped/>
  </testcase> <!-- username -->
  <testcase classname="com.app.testng.FailedTestCases2" name="username" time="0.001">
    <skipped/>
  </testcase> <!-- username -->
  <testcase classname="com.app.testng.FailedTestCases2" name="username" time="0.004">
    <skipped/>
  </testcase> <!-- username -->
  <testcase classname="com.app.testng.FailedTestCases2" name="username" time="0.007">
    <skipped/>
  </testcase> <!-- username -->
  <testcase classname="com.app.testng.FailedTestCases2" name="username" time="0.002">
    <skipped/>
  </testcase> <!-- username -->
  <testcase classname="com.app.testng.FailedTestCases2" name="username" time="0.002">
    <skipped/>
  </testcase> <!-- username -->
  <testcase classname="com.app.testng.FailedTestCases2" name="username" time="0.001">
    <skipped/>
  </testcase> <!-- username -->
  <testcase classname="com.app.testng.FailedTestCases2" name="username" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [a] but found [A]">
      <![CDATA[java.lang.AssertionError: expected [a] but found [A]
at com.app.testng.FailedTestCases2.username(FailedTestCases2.java:10)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- username -->
</testsuite> <!-- Test -->
